### PR TITLE
improve suggestions

### PR DESCRIPTION
**Pull request by JasonWoof**
I found some easier ways to type some words, added several from my log of words I had to look up.

Also changed some [ei]nt- words to use SB. I'm not sure that was I good idea, because you currently can't use that for all [ei]nt- words, but it seems like a useful thing to know about. It saves a stroke on many words.

### CODE REVIEW

**Comment by JasonWoof** [comment]
P.S. I have been reporting the missing SB- briefs to be merged into the Plover defaults but we should probably wait at least 12 months before recommending those.

**Comment by JoshuaGrams** [comment]
Hrm. I'm not sure about `TO` for "to"...I like `O`, and I feel like `TO` is obvious. In general I've been trying to give the shorter stroke when there's one that's just the spelling. Probably not a big deal though.

Also, woo, I wrote this all in Plover, and it wasn't horribly painful.

**Comment by JasonWoof** [comment]
I asked about `TO` vs `O` in discord and consensus was that it's not a big deal, but `TO` should have fewer conflicts.

I decided yesterday that I hit 30wpm average on TypeRacer! I bet I'm slower elsewhere but I'm trying to use steno for everyday writing. It's good mostly.

**Comment by JoshuaGrams** [comment]
Oh. Really? Hrm.

Ah, I see, there are a bunch of words whose strokes begin with `O` but not so many that begin with `TO`. If you filter out the ones where the remainder of the strokes don't make a valid word, there are only 10 `TO/...` translations, and I only see one that would be a problem (and that's probably a goof: I don't see why `TO/VER/SIE` should translate as "Versailles").

But there are 63 `O/...` translations and many of them _would_ be trouble in practice. `O/PIEN` is "opine" rather than "to pine", `O/MEN` is "omen" rather than "to men", `O/VA` is "ova" and not "to have a", etc. etc. etc.

OK, I'm convinced.

**Comment by JasonWoof** [comment]
The other solution is to remove all those O/... definitions and replace them with OE/... definitions. But the jig should teach what works well with the default dictionary.

**Pull request merged**
