### PR TITLE
Styles update

### PR DESCRIPTION
**Pull request by CemraJC**
I like using the steno jig for some practise here and there when I'm not actually writing prose, but the system for choosing drills was a bit hard for me to get my head around at first (especially about the most popular words choices) so I made some changes. I needed to fill time for an afternoon, so I decided to update the styling and typography a bit as well. 

I didn't particularly want to mess with the JavaScript, just styles and the basic HTML structure. Hopefully it doesn't break anything for you -- it works fine for me (but then again, I only tested as far back as Chrome 49 and IE10).

Love the steno-jig -- Thanks for putting in the time! :smile:

### CODE REVIEW

**Comment by CemraJC** [comment]
I should have said -- the link to test it out is <https://cemrajc.github.io/steno-jig>.
I know you could have easily figured it out - just a courtesy I guess :smiley:

**Comment by JoshuaGrams** [comment]
Yeah. That page was just meant to be a quick hack to put something up there, and I've kinda moved on to other things and never replaced it.

I see a few issues with this:

- You converted a whole bunch of tabs to spaces.
- OpenSans has a lowercase L and an uppercase i that are essentially indistinguishable. Also its curly brackets and parentheses are too similar for good readability.
- Binary choices (hints/no hints) should be checkboxes and not pulldown menus.
- This design wastes a lot of space: you've made the font smaller yet pushed significantly more material below the fold for me.
- I like bigger text: that was an intentional decision on my part.

But overall it looks far better: I'll sit down tomorrow evening and incorporate a bunch of this. Thanks!

**Comment by CemraJC** [comment]
Thanks for giving it a look! :smile: 

* Apologies about the tab/spaces thing - my editor must have done it automatically (some setting I probably turned on somewhere).
* I agree that OpenSans would be a poor choice - should have seen it. Roboto Slab (or similar) would be a far better option for readability.
* You're right about the binary options - learned something there :laughing: I can easily add some radio buttons instead.
* If you want the design more compact, I can quickly adjust some margin/padding/widths and pull things up a bit.

And about the big text, I personally don't like it because it clashes with other standard text sizes I'm used to everywhere else on my computer. If the user wants it larger, I guess they can zoom in (but of course, they may not immediately think of that). But, I can agree that for a typing trainer, bigger text in some places makes a lot of sense. But does it have to be inflated everywhere? Totally up to you either way.

I can implement my proposed changes (plus fix the indentation, sorry) and add a new commit some time later tonight.

**Comment by CemraJC** [comment]
Made the changes stated above. Now the only thing pushed below fold is the "Other drills" section on the main form (although it's still clear that the user can scroll). Text is larger where (I think) it matters.

Still open to improvements! :smile:

**Pull request merged**
